### ISSUE TITLE
Question: How do run react-server in production (without react-server-cli)?

### ISSUE THREAD

**Issue by mattiasewers** [redfin/react-server#185]
Firstly, this looks and works amazingly! 

Secondly, I've just played around with code from the yeoman generator for a while now and loveit but I've checked the docs an couldn't find any quides for running `react-server` in production, I assume running `react-server-cli` in production mode is not the right way(please correct me if I'm wrong). Am I supposed use `react-server` as a standalone middleware in express? Please point me in the right directions! Thanks!

**Comment by gigabo** [comment]
Hi @mattiasewers,

Thanks for looking at `react-server`!  You're right, we actually don't use `react-server-cli` in production, but that's mostly because it didn't exist until much later.  We pulled the core of `react-server` out into a stand-alone package so we could open source it, and @aickin set up the `react-server-cli` to fill in some of the gaps that were left.  It actually provides much more than just a CLI:

- A build that generates javascript bundles for client-side use
- Middleware that handles loading those bundles as needed
- A basic express server that ties it all together
- A CLI for configuring it all

Those are all bits that we do separately at Redfin, but actually `react-server-cli` does a nicer job in some ways than we do with our internal build.  The "routes" file format is much nicer, for example.  Medium term we're thinking about how to make those available independent of the "CLI" part of `react-server-cli`.

There are, still, some things that we use internally that we haven't pried out into packages we can share yet (but we're working on it!)

For example:

- A server _cluster_ with:
    - Fault tolerance/isolation
    - Graceful restart
    - Log file management
- A beacon framework for gathering stats and errors from the browser
- A statsd interface to track all those `logger.time` values (this is _crucial_ for us)

Our _goal_ is to make those available as soon as we can and let them integrate easily with `react-server` and `react-server-cli`.

In the short term, I think the answer is probably: Use `react-server-cli --compile-only` and run the build it produces in a custom production server.  We need some documentation on how to do that.

Thanks for calling this out.  I've opened #188 for adding "running in production" documentation.

**Comment by aickin** [comment]
> Use react-server-cli --compile-only and run the build it produces in a custom production server. We need some documentation on how to do that.

You're going to want `--production` on there as well. Also, [there's a section](https://github.com/redfin/react-server/tree/master/packages/react-server-cli#production-mode-optimizing-delivery) of `react-server-cli`'s doc that addresses how to use it in production. 

You are right that it doesn't cover server clustering, beacons, or logging, but I think it's the best answer we have right now, and for many sites it'll be a reasonable answer.

**Comment by gigabo** [comment]
Thanks @aickin!

**Comment by mattiasewers** [comment]
@gigabo Thanks, very thoughtful answer! This is arguably the easiest way to scaffold a react app with ssr, very promising!  

Alright, so ssr would not work in production as of yet? Rather use the client side code splitting that `react-server-cli` outputs? This I have already set up in my production but will definitely use this once sir works in production, get it up and great work! I'll be watching closely!

**Comment by mattiasewers** [comment]
Closing this in favour of #188 

Also, If you don't mind me asking, will `react-server` work with an existing express server without the use of `react-server-cli`, aside from compiling?

**Comment by gigabo** [comment]
Yep!

Just hand the server and the (compiled) routes to the `middleware` function exported by `react-server`:

```javascript
const express = require("express");
const rs      = require("react-server");
const routes  = require("./routes"); // Compiled by `react-server-cli`.

const server  = express();

rs.middleware(server, routes);
```
