### ISSUE TITLE
Dumb Question: How to serve css files?

### ISSUE THREAD

**Issue by withinboredom** [redfin/react-server#227]
I put my built css files into assets/styles.css , however, when I try to load them from the client I get the 404 error: `Cannot GET /assets/styles.min.css`

Am I doing something wrong? Do I need something special in my routes file?

**Comment by doug-wade** [comment]
I get them by `require`-ing them: https://github.com/careylin/ui-kit/blob/master/www/index.js#L3

**Comment by withinboredom** [comment]
:facepalm:

**Comment by withinboredom** [comment]
Uh oh: 

```
ERROR in ./build/assets/fonts/glyphicons-halflings-regular.eot
website_1  | Module parse failed: /app/build/assets/fonts/glyphicons-halflings-regular.eot Line 1: Unexpected token ILLEGAL
```

Looks like a need a custom loader ... any tips to getting that to work?

**Comment by gigabo** [comment]
Ooh... fonts...

We have a ticket open for [custom loader support](https://github.com/redfin/react-server/issues/199).  But a new asset type might be easier have built-in support for, since the development asset servers will need to know about it.  They live right in [`startServer.js`](https://github.com/redfin/react-server/blob/master/packages/react-server-cli/src/startServer.js) for now.

Good issue @withinboredom!

**Comment by aickin** [comment]
@withinboredom Question: I'm assuming you just want to leave the URL in the CSS file, right? You aren't looking for any kind of inlining of the font, I presume.

I could imagine two paths:

- **Quick and dirty**: just add a catch-all loader config with file-loader.
- **Comprehensive**: add an extensible, configurable way to add custom loaders.

I'd vote for quick and dirty for now. Thoughts?

And FYI, I think the particular lines involved are at https://github.com/redfin/react-server/blob/master/packages/react-server-cli/src/compileClient.js#L130

**Comment by gigabo** [comment]
@withinboredom - Closing this as "not a dumb question", and giving the web font issue that spawned from it a dedicated ticket: #233.  Thanks. :)
