### ISSUE TITLE
Web socket error on site

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#487]
https://react-server.io/

![image](https://cloud.githubusercontent.com/assets/115908/17312357/eb318b2a-5806-11e6-8516-a10203a94c3f.png)

@davidalber - Any ideas?

**Comment by davidalber** [comment]
There are a couple things:

1. Some NGINX configuration needs to be done to turn the connection into a WebSocket. See [here](http://nginx.org/en/docs/http/websocket.html).
1. ELB does not support WebSockets. 😞 See below.

The WebSocket is used by [Slackin](https://github.com/rauchg/slackin) to show the number of users on Slack in the badge in realtime. The realtime badge updates work in spite of the error because socket.io has a fallback mechanism. Still, we have the error in the console.

There are options to make the WebSocket work, but ugh. These mostly are the same:
- https://blog.jverkamp.com/2015/07/20/configuring-websockets-behind-an-aws-elb/
- https://gist.github.com/obolton/071be4c926f9cf0b6fd8
- https://www.built.io/blog/websockets-on-aws-s-elb

**Comment by davidalber** [comment]
I've removed the use of the WebSocket from the Slackin that we are using. That was done in a fork I made (see [here](https://github.com/davidalber/slackin/commit/5454341e13e2a6f119826ff6727cba1de4085736)).

I deployed this last night after realizing the operational impact that the WebSocket errors were having on us with high traffic. I haven't investigated why, but each client was making many more of these requests than we previously observed. That was overloading the service. We had a baseline of load balancer 5xx responses with some spikes yesterday. That all went away after this change was deployed.

![image](https://cloud.githubusercontent.com/assets/933552/17632541/c493542e-607d-11e6-88ee-0e00c0b087c1.png)

We were getting tens of thousands of these requests per minute. You can see the drop in requests when the deployment was done.

![image](https://cloud.githubusercontent.com/assets/933552/17632583/084a8b10-607e-11e6-9009-d8766651427f.png)

Those request counts now that are just under 10,000 per minute are mostly 4xx responses:

![image](https://cloud.githubusercontent.com/assets/933552/17632886/93ad3152-607f-11e6-92b3-cf38f161cfd5.png)

Checking the logs, the vast majority of those are the socket.io polling requests. Here are our 2xx responses:

![image](https://cloud.githubusercontent.com/assets/933552/17632938/d8309936-607f-11e6-919b-20420677431d.png)

I don't see any socket.io requests when I load the site now. Given that, and a little reinforcement from the general downward trend of the 4xx line, I conclude that those requests are coming from browsers that loaded the site -- and remain open -- from before the updated Slackin service was deployed. It's a surprising volume!

I will keep watching it independent of this ticket.

**Comment by gigabo** [comment]
Awesome!  Thanks @davidalber!
