### ISSUE TITLE
How to properly bootstrap a react-server app?

### ISSUE THREAD

**Issue by CreepGin** [redfin/react-server#576]
My question stemmed from the need to load some ENV variables from a `.env` file. In other projects, I can use `require('dotenv').config()`. Are there best practices currently in place to deal with such issue right now with react-server?

**Comment by doug-wade** [comment]
I guess my first question is why can't you use [`dotenv`](https://www.npmjs.com/package/dotenv) as is?

For how we do config management, there are two places.  The first is you can store environment-specific react server config in [`.reactserverrc` with the `env` key](https://react-server.io/docs/guides/react-server-cli). The second is we have [config.js](https://github.com/redfin/react-server/blob/master/packages/react-server/core/config.js), which allows you to share config between the server and the client.

**Comment by girvo** [comment]
@doug-wade How does `config.js` work? From the looks of the code, the `rehydrate` method in the client means it's still empty client-side?

**Comment by drewpc** [comment]
@girvo There's an example of how to do this on the [Running a Production Server](https://react-server.io/docs/guides/production) guide.  On the client side, the config object is rehydrated automagically for you.  All you need to do is use the `config()` function inside a React object instance instead of at the root of a module.
