### ISSUE TITLE
Problem with static asset server & secure connections

### ISSUE THREAD

**Issue by hzhu** [redfin/react-server#649]
There are problems with the [static asset server and secure connections](https://react-server.slack.com/archives/discussion/p1472252040000870) recently -- the wrong URL is being passed to the loading middleware.

Deployed react-server [app](https://react-server-redux.herokuapp.com/) is logging an error related to static assets.
<img width="1090" alt="screen shot 2016-08-30 at 12 59 48 pm" src="https://cloud.githubusercontent.com/assets/1811365/18104821/b7f1b1b0-6eb1-11e6-86f3-b21de4047469.png">

**Comment by kennethormandy** [comment]
I’m having this same problem.

The only way I can think of to get around it is to publish the static assets elsewhere and then pass in a `--js-url`, but even that would all need to get deployed on the server because the hashes change vs. compiling locally.

It looks like [this is the line](https://github.com/redfin/react-server/blob/5e3714e119a3b7994adfe441856e43b014e0eb4e/packages/react-server-cli/src/compileClient.js#L58) where the `outputUrl` is used and I think it’s being set incorrectly [here](https://github.com/redfin/react-server/blob/5e3714e119a3b7994adfe441856e43b014e0eb4e/packages/react-server-cli/src/run.js#L33).

I think the protocol is based on the `https` config option instead of whether the request coming into the server is using https, which probably only makes sense in development mode. Maybe a quick fix would be to just use `//` instead of the protocol? I know that’s not the fastest option, but it would be a start.

**Comment by drewpc** [comment]
The next release of `react-server` will include a fix to handle the issue described here.  After it is released, please try it again and let us know if there are any further issues.

**Comment by doug-wade** [comment]
@drewpc this was fixed in #836?

**Comment by drewpc** [comment]
Yes, because it uses a protocol relative request now.
