### ISSUE TITLE
Support for Redux

### ISSUE THREAD

**Issue by sresant** [redfin/react-server#788]
If we are going to support Redux in React Server it seems like we would need a few things.

What comes in mind is some type of RootProvider that would allow us to wrap all RootElements with the redux Provider Element. Also I think it would be helpful to provide some way to wait for specific state in the Redux store and when that state is ready render the RootElement waiting for that state to be available.

Thoughts?

**Comment by mocheng** [comment]
To keep react-server data-management-framework agnostic, it would be better to have this enhancement as another package if possible.

**Comment by gigabo** [comment]
Yes, good point @mocheng!

**Comment by jbenesch** [comment]
> To keep react-server data-management-framework agnostic

I don't really get this... React Server **IS** a data management framework. State is kept in a RLS object (The Model) which is handed to the Page API (The View) in the Client Controller. React is simply the templating language in an otherwise normal MVC OO app.

Really your React "actions" should just be View methods which have a two way data binding with the RLS Model. Very similar to a typical Backbone application.

If React Server wanted to be more Fluxy and support Redux, it would seem like you would want to do something a long the lines of:

1. Remove RLS in favor of creating a redux store
2. Remove Page API in favor of firing a series of well defined actions
3. Remove current custom middleware implementation in favor of Redux Middleware (check out the thunk middleware for an example)

Then my app layer would provide React Server with a Root component (which gets wrapped in a Redux Provider), I could add custom redux middleware to respond to well defined actions that React Server dispatches, and I would provide a root reducer that React Server would use in creating the store.

**Comment by mocheng** [comment]
@jbenesch There are companies that builds products on react-server with data-management-framework other than Redux. For exmaple, redfin is on Reflux, I suppose. So, I would say it is preferred to make  react-server framework agnostic.

It looks it would be more straightforward to manage data with Redux other than RLS. Actually, RLS really upsets me from time to time. But, it would be better to have react-server customizable to adopt Redux, not have Redux bound together.

**Comment by jbenesch** [comment]
So maybe React Server Page API has a concept of a store; `getStore` and the user can provide whatever store they desire. React Server just manages the "if we have a store don't create another one" on every route. Also the serialization of the store's current state and the reboot/rehydration of the store on the client.

You'd still have to deal with dual state managers but I guess you can look at RLS as a global context rather then a store. Would seem like RLS could be evented and you could just subscribe to RLS changes to rerender your views. Then you wouldn't need any other store, just use the built in RLS.

**Comment by ptomasroos** [comment]
This can be closed since #839 @sresant ?
