### ISSUE TITLE
Consolidate HTML + Javascript Servers

### ISSUE THREAD

**Issue by drewpc** [redfin/react-server#807]
This issue serves to simplify the setup of `react-server` and bring all HTTP(S) requests under the same domain.  Currently, if a person configures `react-server` with the following settings:

```
host: 0.0.0.0,
port: 3000,
jsPort: 3001,
hot: true,
```

and opens a browser window pointing to `http://www.myhost.com:3000`, all requests for Webpack files will go to http://0.0.0.0:3001.  Those requests are considered part of a different domain according to the [CORS same-origin policy](https://en.wikipedia.org/wiki/Same-origin_policy#Origin_determination_rules).

Additionally, the `jsPort` requirement is another port that needs to be configured when developing.  This isn't usually a problem when developing on the same machine, but under a Vagrant environment, it can be problematic and unexpected.

Consolidating the HTML + JS servers into a single HTTP/HTTPS server will fix all of these issues and simplify the overall project.  Lastly, it is a stepping stone to further enhancements such as server-side HMR + Webpack configs.

**Comment by aickin** [comment]
> Those requests are considered part of a different domain according to the CORS same-origin policy.

For what it's worth (which, frankly, is maybe not much?), I considered this to be an advantage, because I've often run into problems when my dev experience serves static files and dynamic HTML from the same server. In every production setup I've used, static files are placed on a CDN, so they are subject to CORS restrictions. But when you serve static and dynamic from the same server, the dev experience isn't subject to CORS, and you end up with confusing CORS bugs in prod that are hard to reproduce in the (non-CORS) dev setup. My solution has generally been to simulate a CDN in dev so that both environments are subject to CORS. Thoughts?

**Comment by drewpc** [comment]
@aickin Fair point.  I imagine that this was an unintended side effect instead of an architecture decision, don't you?  I agree that simulating CORS issues prior to moving to production is important.  Do you think that many people realize that `myhost.com:3000` and `myhost.com:3001` are considered different origins?  I didn't until I looked it up to determine what was causing certain issues.  I'd say its not obvious and therefore wouldn't be expected when someone sets up a simple HMR environment.  Just my $0.02.

**Comment by aickin** [comment]
> I imagine that this was an unintended side effect instead of an architecture decision, don't you?

I mean, my memory is notoriously faulty, but I'm pretty sure I set up the CLI with separate JS and HTML servers in order to make sure to simulate CORS issues in dev. Whether that's a good idea or not remains an open question. ;) 

> Do you think that many people realize that myhost.com:3000 and myhost.com:3001 are considered different origins?

I don't know, although I do think that dev understanding of CORS issues in general is fairly low, and CORS errors are indeed extremely confusing for many devs IME.

> I agree that simulating CORS issues prior to moving to production is important. <snip>  I'd say its not obvious and therefore wouldn't be expected when someone sets up a simple HMR environment.

If it's important to simulate CORS before production but simultaneously non-obvious/non-expected to have CORS in dev mode, what do you think is the right thing to do in dev? Do you want to have two different dev modes, one with CORS and one without?

**Comment by roblg** [comment]
Shoot. I feel like I should have seen this one coming. In retrospect, we had to set up CORS headers for our static assets at Redfin, I'm pretty sure because of webpack jsonp loading of `require.ensure` bundles. We definitely had issues when we first released where things worked in dev, and not in production, and it was tough for the people debugging to figure out why.

So... what to do...

One thought: I could imagine keeping the separate server approach, but having the JS HMR server send down the CORS response headers that allow cross-corigin requests. Whether or not this is a good idea depends on if the CORS issues in dev are HMR-specific, or are a symptom of something that would show up in production. I haven't looked myself -- @drewpc do you know if issues you're seeing also appear in bundled JS that isn't using HMR? (On further looking, it appears that we are attempting to send `Access-Control-Allow-Origin` headers via WebpackDevServer in start.js in master?)

I think I could also imagine just consolidating and calling it a day, maybe with an FAQ entry or something in the "productionizing" docs about the same-origin policy, when you might need to work around its restrictions, and how you'd go about doing that. I think that would make react-server's dev setup simpler (good), and less production-y (bad), but maybe it's good enough. Relatedly, if there's anything in "vanilla" react-server that _requires_ CORS headers when deploying to a CDN, we should add that to the docs. We also develop with a single host/port at Redfin, and it's not like we run into CORS issues every week -- it's basically just been once, AFAIK. Take what you will from that information. I will stop short of saying that because we do it that way, it's the right thing to do. :)

Tagging @gigabo directly on this, since I believe he worked on our CORS issue initially.

@drewpc sorry this is taking so long to land. Thanks for sticking with it -- it's much appreciated!

**Comment by drewpc** [comment]
My initial thoughts were that this secondary port was an unintended consequence of trying to use `webpack-dev-server` in combination with the application server itself.  Therefore, this issue & PR was to remove that and consolidate the servers to make it simpler.  I figured the CORS issue (or feature) was a side effect of whatever the architecture decision was.  If the consensus is that the architecture decision was to *introduce* a server with a different origin in order to simulate client code being served from a CDN, then that's a whole different thing.

I'm gonna bow out of the discussion.  As the project maintainers, you all need to figure out what architecture decisions make sense in the long term.  My contributions are simply suggestions.  If consolidating servers is not where you want to go, I'll refactor the server side HMR to not rely on this feature and await the architecture decisions on server side Webpack.

I'm still involved; I just want to contribute things that other people want too!!

**Comment by drewpc** [comment]
FWIW, I refactored PR #809 (server side HMR) and removed the reliance on consolidating servers since this is controversial too!

**Comment by drewpc** [comment]
Addressed in #1003
